### ISSUE TITLE
Rendering in one eye with black background and neon dots when running on Oculus Quest

### ISSUE THREAD

**Issue by xtr33me** [MaximeCordeil/ImAxes#5]
I am well aware this is not supported on the Quest, however I was hoping you might have some advice on why I am seeing what I'm seeing. I am currently trying to get an implementation working in 2019.3.0f3 on the Oculus Quest. The issues I'm dealing with now seem to be shader related and unfortunately I'm not that fluent on the intricacies of shaders. I am currently going through some side projects to gain a better understanding, but I thought I would post here to see if I could find a solution faster with a kick in the right direction. 

First off, it seems graphic shaders aren't really supported on the quest. I have tried a number of hacks but have not had much success.  If I use the existing "Outline Dots" shader, when I bring the axes close to each other and the first collision is detected,I only get a pink vertical line rendering.  When I touch the ends of the axes I get one eye rendering, the overall screen goes black and I see neon dots where the plot points are. (I tried taking a screenshot from the Oculus when the screen was black but it just came out fully black) 

So then I thought I would try just switching out the shader with another. In the current example, I used VRTK/Diffuse_Color.  When doing this I still get the pink vertical line when the first collision is detected, but when I touch the ends of the axes this time, I do get pixels rendering, but they seem to be flipped positionally.  In other words, if my axes represent Quadrant 1, points are being plotted in Quadrant 3. Then when I bring the third Z axes in, I get plotted points that look much more accurate, and pink plot lines.  

Now the plotting works fine when I run it from the Unity Editor, but on device I get this strange behavior.  When I also comment out the include of distort.cginc in the GSBillboard shader and run it in the editor, I get this similar behavior of some points being plotted in the third quadrant (Still not sure they are correct however).  

So my question is whether you can help explain why the points would be plotted inverted. At this point I have accepted to some degree that I will not have any luck getting Geometry Shaders working on the Quest, so do you also have any ideas on how I might be able to get a standard compute shader performing something similar.  If you have any ideas, I'd love to hear them.  

Thanks for the project and if I get something somewhat working here I will make changes and issue a pull request. 

![com nielsen vrdataanalyzer-20200110-141813](https://user-images.githubusercontent.com/1653419/72181755-0343de80-33b8-11ea-9c58-1d242a0a2725.jpg)

![com nielsen vrdataanalyzer-20200110-142352](https://user-images.githubusercontent.com/1653419/72181757-03dc7500-33b8-11ea-8fbf-5fb8338aead9.jpg)

![com nielsen vrdataanalyzer-20200110-142505](https://user-images.githubusercontent.com/1653419/72181758-03dc7500-33b8-11ea-866e-0a32dc5de40c.jpg)

**Comment by atzanteotl** [comment]
Hi Daniel -
Unfortunately ImAxes depends heavily on geometry shaders to have reasonable performance for large datasets. The geometry shaders are used to convert single vertices into quads facing the user. Other aspects of the shaders should work though (vertical and fragment shaders) on the Quest I believe. Let us know how you go.

You can try commenting out just the geometry function of the shader and see if the behaviour makes more sense. It's probable that compute shaders could replace a lot of the functionality, but the pipeline would be fairly different and would result in a lot of work.

**Comment by xtr33me** [comment]
Thanks Andrew.  I will definitely let you know if I get something working decently.  I have accepted that I need to better understand working with shaders, so at this point that is going to be my focus. Then I'm hoping I should be able to perform a rewrite of the components that seem to be having issue running on the Quest. 

I did comment out the GS portion and I also have changed the shader assigned, but one part I have yet to figure out is why the plotted points are offset from the axes themselves.  As you can see in the image, specifically the second one, the purple points are being transitioned away from where the axes are.  Do you have any ideas as to where this is happening? Sure I will find it, but if you have any advice, let me know.  Thanks and I have to say this is one of the coolest uses of VR for data analysis I have seen.  So many others are novelty IMO, but this actually has a practical use.  Awesome job!!

**Comment by atzanteotl** [comment]
The purple points indicate that the shader isn’t running and it’s relying on a default shader instead. When you make a change to a shader and it doesn’t work, Unity usually puts a warning in the shader’s info panel, but doesn’t stop you from running it. Check out the shader info panel - it should provide details of the problem.

When it's working, the shader will distort the points to fit within the boundaries of the axis, so that as you twist and move the axis the scatterplot/PCP will do the same.

**Comment by xtr33me** [comment]
Again....thanks so much Andrew!

**Comment by xtr33me** [comment]
I just wanted to post an update here should anyone else run into something similar.  I still have to get some of the other shaders working, but the scatterplot is now working on the Quest by forcing an MSAA of 0 in Unity.  I had to also uncheck the OVRManager option of "Use recommended MSAA Level" and this is now properly displaying the scatterplot.  Now I need to see if I can get the lines working correctly.
